#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba8ui, binding = 0) uniform uimage2D imgInput;
layout(rgba8, binding = 1) uniform image2D imgOutput;
layout(std430, binding = 2) readonly buffer ColorBuffer {
    vec4 colors[];
};


void main() {
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);

    uvec4 data = imageLoad(imgInput, id);

    imageStore(imgOutput, id, colors[data.r]);
  
}


